INSERT INTO BATSMEN(BATSMAN_ID, NAME, COUNTRY, RUNS) VALUES(30,'WARNER','AUSTRALIA',749);
INSERT INTO BATSMEN(BATSMAN_ID, NAME, COUNTRY, RUNS) VALUES(63,'WILLIAMSON','NEWZLAND',649);
INSERT INTO BATSMEN(BATSMAN_ID, NAME, COUNTRY, RUNS) VALUES(84,'KHOLI','INDIA',784);
INSERT INTO BATSMEN(BATSMAN_ID, NAME, COUNTRY, RUNS) VALUES(61,'SMITH','AUSTRALIA',610);
INSERT INTO BATSMEN(BATSMAN_ID, NAME, COUNTRY, RUNS) VALUES(79,'ROHIT','INDIA',738);
INSERT INTO BATSMEN(BATSMAN_ID, NAME, COUNTRY, RUNS) VALUES(34,'ABD','SOUTH_AFRIKA',748);
INSERT INTO BATSMEN(BATSMAN_ID, NAME, COUNTRY, RUNS) VALUES(61,'MOHAMMAD NABI','AFGHANISTHAN',500);
INSERT INTO BATSMEN(BATSMAN_ID, NAME, COUNTRY, RUNS) VALUES(94,'CHRIS GYLE','WESTINDIES',620);
INSERT INTO BATSMEN(BATSMAN_ID, NAME, COUNTRY, RUNS) VALUES(35,'DUPLISIS','SOUTH_AFRIKA',616);